TI hm.
MiskinAleksandr23/RegularTI pull request #1
Opened 2024-10-26 18:49 UTC by MiskinAleksandr23

2024-10-27 19:42 UTC, MiskinAleksandr23 commented
Я там вторую часть не доделал немного, меня в целом устраивают частичные баллы(если до момента реальной проверки там ничего не поменяется).

2024-11-17 15:04 UTC, katyacyfra approved these changes
Зачтено, -2 балла за отсутствие |

2024-11-26 14:11 UTC, MiskinAleksandr23 commented
part 2.

2024-11-26 16:25 UTC, katyacyfra requested changes
Нет обработки некорректных регулярок (хотелось бы, чтобы программа не просто падала них, а какое-то осмысленное сообщение выводилось, посмотрите на встроенные средства antlr) и соответствующих тестов

2024-12-06 13:25 UTC, katyacyfra approved these changes
Зачтено!

2024-12-18 20:08 UTC, merged